export enum EventName {
  AGENT_STARTED = 'AGENT_STARTED',
  AGENT_COMPLETED = 'AGENT_COMPLETED',
  AGENT_ERROR = 'AGENT_ERROR',
  TOOL_CALLED = 'TOOL_CALLED',
  TOOL_COMPLETED = 'TOOL_COMPLETED',
  WORKFLOW_STARTED = 'WORKFLOW_STARTED',
  WORKFLOW_PAUSED = 'WORKFLOW_PAUSED',
  WORKFLOW_RESUMED = 'WORKFLOW_RESUMED',
  WORKFLOW_COMPLETED = 'WORKFLOW_COMPLETED',
  MEMORY_UPDATED = 'MEMORY_UPDATED',
}
