export enum Permission {
  FILE_READ = 'FILE_READ',
  FILE_WRITE = 'FILE_WRITE',
  FILE_DELETE = 'FILE_DELETE',
  NETWORK_ACCESS = 'NETWORK_ACCESS',
  COMMAND_EXECUTE = 'COMMAND_EXECUTE',
  WORKSPACE_MODIFY = 'WORKSPACE_MODIFY',
}
